### ISSUE TITLE
Fly brain, mouse kidney AnnDatas return 308 error

### ISSUE THREAD

**Issue by RK900** [rs239/schema#2]
I was trying to load in the preprocessed AnnDatas for drosophila and mouse kidneys, but I get a 308 error for both. Have the files been moved somewhere else? The `datasets/` directory doesn't seem to have the h5 files, and the backup URLs in `_datasets.py` redirect me to http://schema.csail.mit.edu.

**Comment by rs239** [comment]
Thanks for catching this! I've now checked in a fix to Github and made a new release (0.1.5.3) that fixes the backup URL. Pls confirm that this works on your end?

Re the workflow: the first time you call schema.datasets.fly_brain(), it will create a datsets/ folder in your run directory and download the .h5 file from an MIT server. In subsequent calls to schema.datasets.fly_brain(), the code will check the sub-dir location and load the file from there.

**Comment by RK900** [comment]
Works!
